services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  backend:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb

volumes:
  data: