name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        
      - name: Install dependecies
        run: npm install

      - name: Test code
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build image
        run: docker build -t $DOCKER_USERNAME/nodepost .

      - name: Push image
        run: docker push $DOCKER_USERNAME/nodepost